### ISSUE TITLE
Problem concerning JSON.SET

### ISSUE THREAD

**Issue by YumingZHAI** [RedisLabsModules/rejson#28]
Hello, I've installed redis-4.0-rc3 and rejson module, and the test passed at root:

```
YumingdeMacBook-Pro:rejson yumingzhai$ make test
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./test all
cc -I"/Users/yumingzhai/Downloads/rejson/test/../src" -I"/Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl"  -I"/Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_object.out test_object.c /Users/yumingzhai/Downloads/rejson/test/../src/librejson.a /Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl/libjsonsl.a -lm 
cc -I"/Users/yumingzhai/Downloads/rejson/test/../src" -I"/Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl"  -I"/Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o test_json_object.out test_json_object.c /Users/yumingzhai/Downloads/rejson/test/../src/librejson.a /Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl/libjsonsl.a -lm
cc -I"/Users/yumingzhai/Downloads/rejson/test/../src" -I"/Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl"  -I"/Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil" -Wall -g -ggdb -O2  -std=gnu99 -D_GNU_SOURCE -mmacosx-version-min=10.6 -o json_validator.out json_printer.c /Users/yumingzhai/Downloads/rejson/test/../src/librejson.a /Users/yumingzhai/Downloads/rejson/test/../deps/RedisModuleSDK/rmutil/librmutil.a /Users/yumingzhai/Downloads/rejson/test/../deps/jsonsl/libjsonsl.a -lm
./test_object.out
.......................................................................................................................................................................................................................

8 tests, 215 assertions, 0 failures

Finished in 0.00017183 seconds (real) 0.00012900 seconds (proc)

./test_json_object.out
............................................................................................................................

17 tests, 124 assertions, 0 failures

Finished in 0.00030962 seconds (real) 0.00022300 seconds (proc)

./test_json_validator.sh

Should PASS: ........................................
Should FAIL: .......................................................................

111 JSON files validated, 0 problems detected
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C pytest
python -m unittest discover
.........................
----------------------------------------------------------------------
Ran 25 tests in 3.095s

OK
```

But it failed in the repertory pytest:
```
YumingdeMacBook-Pro:pytest yumingzhai$ REDIS_PORT=6379 make
python -m unittest discover
Redis output: 83380:C 04 Jul 12:08:42.759 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
83380:C 04 Jul 12:08:42.760 # Redis version=3.9.103, bits=64, commit=00000000, modified=0, pid=83380, just started
83380:C 04 Jul 12:08:42.760 # Configuration loaded
83380:M 04 Jul 12:08:42.761 * Increased maximum number of open files to 10032 (it was originally set to 256).
83380:M 04 Jul 12:08:42.761 # Creating Server TCP listening socket *:6379: bind: Address already in use

[... many errors here...]


======================================================================
ERROR: testStrCommands (test.ReJSONTestCase)
Test JSON.STRAPPEND and JSON.STRLEN commands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 581, in testStrCommands
    self.assertOk(r.execute_command('JSON.SET', 'test', '.', '"foo"'))
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: unknown command 'JSON.SET'

======================================================================
ERROR: testTypeCommand (test.ReJSONTestCase)
Test JSON.TYPE command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 489, in testTypeCommand
    self.assertOk(r.execute_command('JSON.SET', 'test', '.', json.dumps(v)))
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: unknown command 'JSON.SET'

----------------------------------------------------------------------
Ran 25 tests in 0.359s

FAILED (errors=23)
make: *** [test] Error 1
```

Now I can load Rejson module with redis, and use Rejson commands in redis-cli: 
```
YumingdeMacBook-Pro:src yumingzhai$ redis-server --loadmodule /Users/yumingzhai/Downloads/rejson/src/rejson.so
82846:C 04 Jul 11:52:40.465 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
82846:C 04 Jul 11:52:40.466 # Redis version=3.9.103, bits=64, commit=00000000, modified=0, pid=82846, just started
82846:C 04 Jul 11:52:40.466 # Configuration loaded
82846:M 04 Jul 11:52:40.467 * Increased maximum number of open files to 10032 (it was originally set to 256).
82846:M 04 Jul 11:52:40.467 # Creating Server TCP listening socket *:6379: bind: Address already in use

YumingdeMacBook-Pro:src yumingzhai$ redis-cli
127.0.0.1:6379> JSON.SET foo . 6
OK
127.0.0.1:6379> JSON.GET foo
"6"

```

But it doesn't work in these two cases with python: 
```
YumingdeMacBook-Pro:src yumingzhai$ python
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import redis
>>> import json
>>> data = {
...     'foo': 'bar'
... }
>>> 
>>> r = redis.StrictRedis()
>>> r.execute_command('JSON.SET', 'doc', '.', json.dumps(data))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'JSON.SET'
```
```
YumingdeMacBook-Pro:rejson yumingzhai$ python 
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from rejson import Client, Path
>>> rj = Client(host='localhost', port=6379)
>>> obj={ 'foo': 'bar', 'ans':42}
>>> rj.jsonset('obj',Path.rootPath(),obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/rejson/client.py", line 142, in jsonset
    return self.execute_command('JSON.SET', *pieces)
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/yumingzhai/anaconda2/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'JSON.SET'
```

I don't know where the problem comes from, could you help me with this issue? Thanks!

**Comment by dvirsky** [comment]
Sounds like you have a running redis server that is not loading rejson, implied by `83380:M 04 Jul 12:08:42.761 # Creating Server TCP listening socket *:6379: bind: Address already in use`.

**Comment by itamarhaber** [comment]
What @dvirsky said :)

**Comment by YumingZHAI** [comment]
Thanks so much for helping! I've shutdown the running server by **redis-cli shutdown**, and restarted and loaded the module, it works perfectly now :)
